version: '3.4'
services:
  app:
    build: .
    # command: streamlit run src/app.py --server.port 8501
    environment:
      MPLCONFIGDIR: /etc
      ENVIRONMENT: dev
    volumes:
      - ./:/app
    ports:
      - '8501:8501'
